#!/bin/bash -e

# Very simple script to build the Puppet Enterprise stack on SLES11.
# You need to have a RPM which satisfy the dependency "pe-puppet-enterprise-release".

set -o pipefail

skip="true"

loop_packages() {
	echo
	echo "=== $i ==="
	specfile=$1

	name=`echo $1 | perl -ane 's/\.spec//; print'`
	echo "n: $name s: $specfile"

	rpm -qa | grep -E ^"${name}-[0-9]" && [[ $skip -eq "true" ]] && echo "-- skipping $name" && continue
  echo "-- building"
	out=`rpmbuild -bb /usr/src/packages/SPECS/${specfile} | perl -lane 'print $1, if m/^Wrote: (.*\.rpm)$/'`
	echo "-- installing binary package(s)"
	rpm -ivh --replacepkgs $out

}

list="
pe-libyaml.spec
pe-ruby.spec
pe-facter.spec
pe-augeas.spec
pe-rubygem-deep-merge.spec
pe-hiera.spec
pe-ruby-rgen.spec
pe-ruby-shadow.spec
pe-puppet.spec
pe-java.spec
pe-tanukiwrapper.spec
pe-activemq.spec
pe-ruby-stomp.spec
pe-mcollective.spec
pe-bundler.spec
pe-httpd.spec
pe-ruby-augeas.spec
pe-rubygem-rack.spec
pe-passenger.spec
pe-libevent.spec
pe-rubygem-activesupport.spec
pe-rubygem-activerecord.spec
pe-rubygem-builder.spec
pe-rubygem-excon.spec
pe-rubygem-formatador.spec
pe-rubygem-mime-types.spec
pe-rubygem-multi-json.spec
pe-rubygem-net-ssh.spec
pe-rubygem-net-scp.spec
pe-rubygem-nokogiri.spec
pe-rubygem-ruby-hmac.spec
pe-rubygem-fog.spec
pe-rubygem-guid.spec
pe-rubygem-rbvmomi.spec
pe-rubygem-sequel.spec
pe-rubygem-trollop.spec
pe-ruby-ldap.spec
pe-ruby-mysql.spec
pe-puppetdb.spec
pe-postgresql.spec
pe-puppet-dashboard.spec
pe-rubygem-sinatra.spec
"

#
# Havent gotten these to build yet. Drop me a line if you can build these.
#
# pe-rubycas-server.spec
# pe-memcached.spec


for i in $list
do
	loop_packages $i
done
