#!/bin/bash -e

# Very simple script to build the Puppet Enterprise 3.1.2 stack on SLES10.
# You need to have a RPM called "pe-puppet-enterprise-release" installed.

set -o pipefail

skip="true"

loop_packages() {
	echo
	echo "=== $i ==="
	specfile=$1

	name=`echo $1 | perl -ane 's/\.spec//; print'`
	echo "n: $name s: $specfile"

	rpm -qa | grep -E ^"${name}-[0-9]" && [[ $skip -eq "true" ]] && echo "-- skipping $name" && continue
  echo "-- building"
	out=`rpmbuild -bb /usr/src/packages/SPECS/${specfile} | perl -lane 'print $1, if m/^Wrote: (.*\.rpm)$/'`
	echo "-- installing binary package(s)"
	rpm -ivh --replacepkgs $out

}

list="
pe-libyaml.spec
pe-ruby.spec
pe-facter.spec
pe-augeas.spec
pe-rubygem-deep-merge.spec
pe-hiera.spec
pe-ruby-rgen.spec
pe-ruby-shadow.spec
pe-puppet.spec
pe-tanukiwrapper.spec
pe-activemq.spec
pe-ruby-stomp.spec
pe-mcollective.spec
pe-bundler.spec
pe-ruby-augeas.spec
pe-rubygem-rack.spec
pe-libevent.spec
pe-rubygem-activesupport.spec
pe-rubygem-activerecord.spec
pe-rubygem-builder.spec
pe-rubygem-excon.spec
pe-rubygem-formatador.spec
pe-rubygem-mime-types.spec
pe-rubygem-multi-json.spec
pe-rubygem-net-ssh.spec
pe-rubygem-net-scp.spec
pe-rubygem-nokogiri.spec
pe-rubygem-ruby-hmac.spec
pe-rubygem-fog.spec
pe-rubygem-guid.spec
pe-rubygem-rbvmomi.spec
pe-rubygem-sequel.spec
pe-rubygem-trollop.spec
pe-ruby-ldap.spec
pe-ruby-mysql.spec
pe-puppetdb.spec
pe-postgresql.spec
"

# I have not yet gotten to get the below RPMs to build. I only needed a Puppet agent and the MCollective client on my SLES10 systems, so it wasent worth the effort for me. If you manage to get these to build on SLES10 then please let me know.
#
# pe-httpd.spec
# pe-passenger.spec
# pe-puppet-dashboard.spec
# pe-rubygem-sinatra.spec
# pe-memcached.spec
# pe-rubycas-server.spec
# pe-java (I use the SLES11 RPM instead)
#


for i in $list
do
	loop_packages $i
done

